use_default_settings: true

general:
  instance_name: "searxng"

server:
  secret_key: "f7a389f4b18c99b82f0c763198a44b9d"

search:
  autocomplete: "google"
  formats:
    - html
    - json

enabled_engines:
  - google
  - bing
  - duckduckgo
  - wikipedia
  - brave
  - mojeek
  - startpage
  - wiby
  - yahoo
  - 9gag
  - lemmy comments
  - lemmy communities
  - lemmy posts
  - lemmy users
  - mastodon hashtags
  - mastodon users
  - reddit
  - tootfinder
